subscriptionCondition=订阅条件
recoveryPlanExecutionStatus=业务抢通方案执行状态
complaintDiagnosisTaskId=投诉诊断任务流水号
ossEventId=OSS侧事件流水号
accessPortName=接入端口名称
omcAutoRecoveryAuthorized=是否已授权OMC自动抢通
recoveryPlanName=业务抢通方案名称
recoveryPlanDetail=业务抢通方案详情
recoveryPlanEndTime=业务抢通方案执行结束时间
recoveryPlanExecutionResult=业务抢通方案执行结果
recoveryPlanFailureReason=业务抢通方案执行失败原因
